[package]
name = "inline_default"
version = "1.1.0"
edition = "2021"

description = "Macro for inline Default implementation."
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["default", "macro", "no_std", "utility"]
categories = ["rust-patterns"]
